### ISSUE TITLE
Scaffolding error

### ISSUE THREAD

**Issue by AnnaSyme** [slimsuite/pafscaff#2]
Hi Rich

I am trying PafScaff on some test data to see if I can get the expected output files. 

Data: 
Reference genome: Arabidopsis thaliana fasta file from https://www.ncbi.nlm.nih.gov/assembly/GCA_000001735.2/ - chromosome level assembly (7 chroms)

Assembly genome: Arabidopsis halleri fasta file from https://www.ncbi.nlm.nih.gov/assembly/GCA_000523005.1/ - scaffold level assembly (~300,000 scaffolds)

running with:

``` 
python code/pafscaff.py reference=arabithali.fasta assembly=arabihal.fasta
```

Outputs: 
placed.fasta
anchored.fasta
unplaced.fasta (empty)
No scaffolds file

Error message (tail of error log):

```
#~~#	00:00:25	# ~~~~~~~~~~~~~~ Output pafscaff scaffolds ~~~~~~~~~~~~~~~ #
#ERR	00:00:38	PAFScaff.scaffold error: <type 'KeyError'> (scaffold line 734) 'FJVB01002239.1'  
#ERR	00:00:38	A ghostly child with a man of truth programs but the strong monkey ponders peril: <type 'ValueError'> (run line 497) Scaffolding error  
#ERR	00:00:38	Fatal error in main PAFScaff run.: <type 'ValueError'> (run line 497) Scaffolding error  
#WARN	00:00:38	3 error messages! Check log for details.
#LOG	00:00:38	PAFScaff V0.4.1 End: Tue Apr 20 17:17:46 2021
```

Do you know why there would be no scaffolds file? 

I've tried running with appending the option ```scaffold=T``` but no difference. 

Thanks! 

Attached:
log file 
[pafscaff.log](https://github.com/slimsuite/pafscaff/files/6341566/pafscaff.log)

**Comment by cabbagesofdoom** [comment]
Hi @AnnaSyme. There is no output because it crashed. Now the question becomes... why did it crash? I think I should have everything I need to dig into this, but I will let you know if I get stuck. (I'll also sanitise some of the error messages, a little! My random "Zen wisdom" generator is fun for debugging but maybe not so appropriate for public consumption!)

I will also try to improve the documentation a little and add check for things that may give problems. 

PS. Your example data made me sweat a little - not sure how it would handle 300k sequences, as it's designed with closer to chromsome-level in mind - but I think it might be ~300k contigs? It appears to only have 2,239 scaffolds from the log.

**Comment by cabbagesofdoom** [comment]
Hi @AnnaSyme, I've downloaded `GCA_000523005.1_Ahal_1.0_genomic.fna` but it is indeed in nearly 300k pieces and does not include the sequence `FJVB01002239.1` anywhere. I'll update the code to handle the problem it's encountering (even though I am not sure why at this point), but if you can share the `arabihal.fasta` file with me then I can test it properly.

**Comment by AnnaSyme** [comment]
Thanks @cabbagesofdoom for looking into it - I will email the fasta files now. The part of the error that refers to the sequence of `FJVB01002239.1` - this changes according to the input files, for example, on some other files, the error referred to `PAFScaff.scaffold error: <type 'KeyError'> (scaffold line 734) 'contig_1'`, but there was no `contig 1` then either, although there were contigs that were numbered like contig_1123 etc. So I wondered if it was taking a prefix from somewhere and ... doing something.

**Comment by cabbagesofdoom** [comment]
Hi @AnnaSyme, I've reproduced the error and hopefully fixed it, so no need for the files now. If you want a quick fix whilst I am testing, run with the `unplaced=X` setting to give the unplaced scaffolds a new name (e.g. `unplaced=UNPLACED`). There was a rogue counter that should not have been accessed without that setting, but was.

I'm a bit disturbed about sequence names not in the input, though. That really should not happen. Have you been renaming different files as `arabihal.fasta` and leaving the `arabihal.fasta.index` file there, by any chance? (This should not cause a problem unless the timestamps are wonky, but I can't think of other causes at this point.) Or re-running in the same directory without deleting the previous run?

**Comment by AnnaSyme** [comment]
Thanks @cabbagesofdoom will re-try! Yes sometimes I have been forgetting to delete previous runs and was wondering if that was a problem, but I think on that most recent error I had started from a clean directory.

**Comment by cabbagesofdoom** [comment]
Unless run with `force=T` (and not 100% sure that's implemented in PAFScaff), PAFScaff will reload pre-existing results and resume from the last step. It will get confused if the input changes but the output is still there with the same name. I highly recommend setting `basefile=X`, which will set the prefix for all output including the log, and prevent clashes. (This also enables simultaneous runs in the same directory.)

**Comment by AnnaSyme** [comment]
This worked - 

running with `unplaced=X` and `basefile=arabi` 

Many thanks!

**Comment by cabbagesofdoom** [comment]
The updated `v0.4.2` should fix this problem.
